[package]
name = "libcamlite-rs-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = {version = "7.1.0", features=["rpi"]}
ffmpeg-sys-next = "7.1.0"
rslibcamlite = { path = "../libcamlite-rs" }

